#!url=https://raw.githubusercontent.com/ItzXunn/xunn/refs/heads/main/spotify.module
#!name=Spotify 💚
#!desc=Mở khoá tính năng Spotify Individual. Khuyến nghị đăng nhập lại sau khi cài đặt. Hỗ trợ âm thanh chất lượng cao cấp.
# 🩷 Discord: https://discord.gg/rabbitstore
# 🤍 Release by: Xunn | TheSword Studio
#!author=Xunn[https:instagram.com/itzxunn_]
#!openUrl=https://apps.apple.com/app/id324684580
#!tag=VN
[Script]
JSON处理 = type=http-request, pattern=^https:\/\/spclient\.wg\.spotify\.com\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/, script-path=https://kelee.one/Resource/Script/Spotify/Spotify_remove_ads.js, timeout=10

Proto处理 = type=http-response, pattern=^https:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$, script-path=https://kelee.one/Resource/Script/Spotify/Spotify_proto.js, requires-body=true, binary-body-mode=true, timeout=10

[MITM]
hostname = %APPEND% spclient.wg.spotify.com
